#!/bin/bash
# MANUAL SETUP - Jalankan command ini satu per satu

echo "════════════════════════════════════════════════════════════════"
echo "SETUP DATABASE HK-NOVA - MANUAL STEPS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Karena MySQL memerlukan password, silakan jalankan command berikut:"
echo ""
echo "1. Buat database:"
echo "   mysql -u root -p"
echo "   # Masukkan password MySQL Anda"
echo "   # Kemudian di MySQL prompt, ketik:"
echo "   CREATE DATABASE hk_nova_dev CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "   SHOW DATABASES;"
echo "   EXIT;"
echo ""
echo "2. Update .env dengan password MySQL:"
echo "   nano .env"
echo "   # Ubah baris DATABASE_URL:"
echo "   # Dari: DATABASE_URL=\"mysql://root:@localhost:3306/hk_nova_dev\""
echo "   # Jadi: DATABASE_URL=\"mysql://root:PASSWORD_ANDA@localhost:3306/hk_nova_dev\""
echo "   # Ganti PASSWORD_ANDA dengan password MySQL Anda"
echo "   # Save: Ctrl+X, Y, Enter"
echo ""
echo "3. Push schema ke database:"
echo "   export PATH=~/.npm-global/bin:\$PATH"
echo "   cd /home/gopal-ichiro/Documents/magang/hk-nova"
echo "   pnpm db:push"
echo ""
echo "4. Generate Prisma Client:"
echo "   pnpm generate"
echo ""
echo "5. Seed demo data:"
echo "   pnpm db:seed"
echo ""
echo "6. Test aplikasi:"
echo "   pnpm dev"
echo "   # Buka: http://localhost:3000"
echo "   # Login: admin / admin123"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "ATAU gunakan script otomatis:"
echo "   bash setup-mysql.sh"
echo "   bash quick-setup.sh"
echo "════════════════════════════════════════════════════════════════"
