import prisma from '@/lib/prisma';
import { ServiceType, CustomerStatus } from '@prisma/client';

const FIRST_NAMES = [
  'Ahmad', 'Budi', 'Citra', 'Dewi', 'Eko', 'Fajar', 'Gita', 'Hadi', 'Indah', 'Joko',
  'Kartika', 'Luki', 'Maya', 'Nugroho', 'Oki', 'Putri', 'Qori', 'Rian', 'Siti', 'Tono',
  'Utami', 'Vina', 'Wawan', 'Xena', 'Yudi', 'Zahra', 'Andi', 'Bambang', 'Cahyo', 'Dian',
];

const LAST_NAMES = [
  'Santoso', 'Wijaya', 'Saputra', 'Pratama', 'Kusuma', 'Hidayat', 'Nugraha', 'Setiawan',
  'Ramadhan', 'Laksana', 'Suryono', 'Utomo', 'Wibowo', 'Firmansyah', 'Ginting', 'Siregar',
  'Hutapea', 'Sitorus', 'Nasution', 'Lubis', 'Wong', 'Tan', 'Lee', 'Chandra', 'Suharto',
];

const PACKAGES = [
  { name: 'Paket 10Mbps', upload: 10000, download: 10000, fee: 150000, type: ServiceType.PPPOE },
  { name: 'Paket 20Mbps', upload: 20000, download: 20000, fee: 250000, type: ServiceType.PPPOE },
  { name: 'Paket 50Mbps', upload: 50000, download: 50000, fee: 450000, type: ServiceType.PPPOE },
  { name: 'Paket 100Mbps', upload: 100000, download: 100000, fee: 750000, type: ServiceType.PPPOE },
  { name: 'Paket Corporate 50Mbps', upload: 50000, download: 50000, fee: 1000000, type: ServiceType.DHCP },
  { name: 'Paket Corporate 100Mbps', upload: 100000, download: 100000, fee: 180000, type: ServiceType.DHCP },
];

function getRandomItem<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

function getRandomNumber(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function generateMacAddress(): string {
  const hex = '0123456789ABCDEF';
  let mac = '00:11:22:';
  for (let i = 0; i < 3; i++) {
    mac += hex[Math.floor(Math.random() * 16)] + hex[Math.floor(Math.random() * 16)];
    if (i < 2) mac += ':';
  }
  return mac;
}

async function generateTestCustomers(count: number = 300) {
  console.log(`🚀 Generating ${count} test customers...`);

  const devices = await prisma.device.findMany({
    where: {
      OR: [
        { type: 'ROUTER' },
        { vendor: { contains: 'MikroTik' } },
      ],
    },
  });

  if (devices.length === 0) {
    console.error('❌ No devices found. Please seed devices first.');
    process.exit(1);
  }

  console.log(`✅ Found ${devices.length} devices for load distribution`);

  let createdCount = 0;
  let skippedCount = 0;

  for (let i = 1; i <= count; i++) {
    const username = `loadtest_${String(i).padStart(4, '0')}`;
    const firstName = getRandomItem(FIRST_NAMES);
    const lastName = getRandomItem(LAST_NAMES);
    const fullName = `${firstName} ${lastName}`;
    const phone = `08${getRandomNumber(1000000000, 9999999999)}`;
    const email = `${username}@example.com`;
    const address = `Jl. Load Test No. ${i}, Jakarta`;
    const pkg = getRandomItem(PACKAGES);
    const device = getRandomItem(devices);

    const isPPPoE = pkg.type === ServiceType.PPPOE;
    const isOnline = Math.random() > 0.3; // 70% online
    const statusRand = Math.random();
    
    let status: CustomerStatus = CustomerStatus.ACTIVE;
    if (statusRand > 0.85) status = CustomerStatus.SUSPENDED; // 15% suspended
    else if (statusRand > 0.95) status = CustomerStatus.PENDING; // 5% pending

    try {
      const existing = await prisma.customer.findUnique({
        where: { username },
      });

      if (existing) {
        skippedCount++;
        continue;
      }

      await prisma.customer.create({
        data: {
          username,
          fullName,
          phoneNumber: phone,
          email,
          address,
          serviceType: pkg.type,
          pppoePassword: isPPPoE ? `Pass${i}123!` : null,
          pppoeProfile: isPPPoE ? 'default' : null,
          ipAddress: !isPPPoE ? `10.10.${Math.floor(i / 250)}.${(i % 250) + 1}` : null,
          macAddress: !isPPPoE ? generateMacAddress() : null,
          dhcpServer: !isPPPoE ? 'dhcp1' : null,
          uploadSpeed: pkg.upload,
          downloadSpeed: pkg.download,
          packageName: pkg.name,
          status,
          isOnline: status === CustomerStatus.ACTIVE ? isOnline : false,
          lastSeen: isOnline ? new Date() : new Date(Date.now() - getRandomNumber(3600000, 86400000)),
          activationDate: new Date(Date.now() - getRandomNumber(86400000, 31536000000)),
          billingCycle: 'MONTHLY',
          monthlyFee: pkg.fee,
          deviceId: device.id,
          createdBy: 'load-test-generator',
          notes: `Generated by load test script (${pkg.name})`,
        },
      });

      createdCount++;

      if (i % 50 === 0) {
        console.log(` progress: ${i}/${count} customers generated...`);
      }

    } catch (error) {
      console.error(`❌ Failed to create customer ${username}:`, error);
    }
  }

  console.log('');
  console.log('🎉 Generation completed!');
  console.log(`   Created: ${createdCount}`);
  console.log(`   Skipped: ${skippedCount}`);
  console.log(`   Total in DB: ${await prisma.customer.count()}`);
  console.log('');
}

generateTestCustomers(300)
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
  });
